version: '3.1'

services:
  pokemon-db:
    image: mysql
    volumes:
      - pokemon-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhaBase
      MYSQL_DATABASE: pokemon_db
    ports:
      - "1010:3306"
  treinador-db:
    image: mysql
    volumes:
      - treinador-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhaBase
      MYSQL_DATABASE: treinador_db
    ports:
      - "1011:3306"
  professor-db:
    image: mysql
    volumes:
      - professor-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhaBase
      MYSQL_DATABASE: professor_db
    ports:
      - "1012:3306"
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    volumes:
      - rabbit:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  pokemon-db:
  treinador-db:
  professor-db:
  rabbit:
